tg greeting
PabloBullies/StudyConnectTGGateway pull request #2
Opened 2024-10-01 16:48 UTC by xDm1try

Основа для бота готова. Нужно расширение функционала

2024-10-05 05:45 UTC, Foxtezy requested changes

2024-10-05 05:45 UTC, Foxtezy commented on src/main/java/gigachadus/StudyConnect/config/BotInitializer.java
> +    TelegramBot bot;
Не используем Autowired на полях. Делай как Влад в сервисах через RequiredArgsConstructor

2024-10-05 05:45 UTC, Foxtezy commented on src/main/java/gigachadus/StudyConnect/config/BotInitializer.java
> +    @EventListener({ContextRefreshedEvent.class})
Вот тут требуются пояснения почему это именно через Event listener сделано

2024-10-05 05:45 UTC, Foxtezy commented on src/main/java/gigachadus/StudyConnect/service/AccountManager.java
> +@Component
Ну это явно @Service

2024-10-05 05:45 UTC, Foxtezy commented on src/main/java/gigachadus/StudyConnect/service/TelegramBot.java
> +@PropertySource("application.properties")
Вот эту хрень как будто можно не указывать

2024-10-05 05:45 UTC, Foxtezy commented on src/main/java/gigachadus/StudyConnect/config/BotInitializer.java
> +    TelegramBot bot;
ну и где private final

2024-10-05 05:45 UTC, Foxtezy commented on src/main/java/gigachadus/StudyConnect/service/TelegramBot.java
> +    final BotConfig config;
private final

2024-10-05 05:45 UTC, Foxtezy commented on src/main/java/gigachadus/StudyConnect/config/BotConfig.java
> +    public String getBotName() {
Ладно, используй ломбок, разрешаю. Хотя здесь вроде и рекорды подойдут

2024-10-05 05:45 UTC, Foxtezy commented on src/main/java/gigachadus/StudyConnect/service/TelegramBot.java
> +@PropertySource("application.properties")
И я не вижу этот файл. Даже если там пароли, он всё равно должен быть. Просто значения должны быть пустые и подствавляться в параметрах запуска

2024-10-19 03:03 UTC, xDm1try commented
Пофиксил недостатки

2024-10-19 03:04 UTC, xDm1try commented on src/main/java/gigachadus/StudyConnect/config/BotInitializer.java
> +    @EventListener({ContextRefreshedEvent.class})
Происходит во время инициализации или смены контекста. Необходимо каждый раз переинициализировать бота

2024-10-19 03:26 UTC, Foxtezy requested changes

2024-10-19 03:26 UTC, Foxtezy commented on src/main/java/gigachadus/StudyConnect/service/TelegramBot.java
> +@PropertySource("application.properties")
Так нужно или нет указывать, он же автоматом application.properties подтягивать

2024-10-19 03:26 UTC, Foxtezy commented on src/test/java/gigachadus/StudyConnect/StudyConnectApplicationTests.java
> +class StudyConnectApplicationTests {
Этот класс либо удали, либо удали аннотацию @SpringBootTest

2024-10-19 03:26 UTC, Foxtezy commented on src/main/java/gigachadus/StudyConnect/config/BotInitializer.java
> +    public BotInitializer(TelegramBot bot) {
Кринге, я ж сказал что можно ломбок использовать, там есть аннотация @RequairedArgsConstructor

2024-10-19 03:26 UTC, Foxtezy commented on src/main/java/gigachadus/StudyConnect/config/BotConfig.java
> +    String botName;
Лучше сделай инициализацию через конструктор, чтоб в тестах не надо было ApplicationContext поднимать

2024-10-19 03:26 UTC, Foxtezy commented on src/main/java/gigachadus/StudyConnect/config/BotConfig.java
> +    public String getBotName() {
Так это, добавь аннотацию, вроде @Getters называется

2024-10-19 03:26 UTC, Foxtezy commented on src/main/java/gigachadus/StudyConnect/config/BotConfig.java
> +@PropertySource("application.properties")
тоже есть подозрение что это не обязательно

2024-10-19 03:32 UTC, xDm1try commented on src/main/java/gigachadus/StudyConnect/config/BotInitializer.java
> +    public BotInitializer(TelegramBot bot) {
Идея этого не понимает. Сделал так,чтобы не ругалась

2024-10-19 03:52 UTC, Foxtezy requested changes

2024-10-19 03:52 UTC, Foxtezy commented on src/main/java/gigachadus/StudyConnect/config/BotConfig.java
>      String botToken;
private final емае

2024-10-19 04:09 UTC, xDm1try commented on src/main/java/gigachadus/StudyConnect/config/BotConfig.java
>      String botToken;
done

2024-10-19 04:44 UTC, Foxtezy approved these changes
ладно

2024-10-26 03:24 UTC, merged